name: cmake-reusable
run-name: cmake-reusable

on: 
  workflow_dispatch:
    inputs:
      base_artifact_filename:
        description: >
          "The base filename of the artifact .zip that is created OS and
          architecture are appended"
        required: false
        default: "Binexport"
        type: string
      binaryninja_build_channel:
        description: >
          "Set to stable for the latest stable build or dev for the nightly 
          build. A commit hash can also be specified"
        required: false
        default: "stable"
        type: string
      build_type:
        description: "Debug or Release builds"
        required: false
        default: "Release"
        type: string
      enable_binaryninja_build:
        description: "Set to ON to enable the binaryninja build or OFF to disable."
        required: false
        default: "ON" 
        type: string
      enable_idapro_build:
        description: "Set to ON to enable the IDA Pro build or OFF to disable."
        required: false
        default: "ON" 
        type: string

  workflow_call:
    inputs:
      base_artifact_filename:
        description: >
          "The base filename of the artifact .zip that is created OS and
          architecture are appended"
        required: false
        default: "Binexport"
        type: string
      binaryninja_build_channel:
        description: >
          "Set to stable for the latest stable build or dev for the nightly 
          build. A commit hash can also be specified"
        required: false
        default: "stable"
        type: string
      build_type:
        description: "Debug or Release builds"
        required: false
        default: "Release"
        type: string
      enable_binaryninja_build:
        description: "Set to ON to enable the binaryninja build or OFF to disable."
        required: false
        default: "ON" 
        type: string
      enable_idapro_build:
        description: "Set to ON to enable the IDA Pro build or OFF to disable."
        required: false
        default: "ON" 
        type: string
    secrets:
      IDASDK_SECRET:
        description: "The password for unzipping the IDA SDK zip."
        required: false

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-22.04
          boost_platform_version: 22.04
          boost_toolset: gcc
          boost_arch: x86
        - os: macos-13
          boost_platform_version: 13
          boost_toolset: clang
          boost_arch: x86
        - os: macos-14
          boost_platform_version: 14
          boost_toolset: clang
          boost_arch: aarch64
        - os: windows-2022
          boost_platform_version: 2022
          boost_toolset: msvc
          boost_arch: x86
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v6

    - name: Create Build Directory 
      working-directory: ${{ github.workspace }}
      shell: bash
      run: mkdir -p "${{ github.workspace }}/build"
      
    - name: Unzip IDA SDK
      working-directory: ${{ github.workspace }}
      env:
        IDASDK_SECRET: ${{ secrets.IDASDK_SECRET }}
      if: env.IDASDK_SECRET != ''
      run: |
        ./.github/scripts/decrypt_secret.sh
        unzip -q "${{ github.workspace }}/build/idasdk_teams82.zip" \
              -d "${{ github.workspace }}/build/"

    - name: Enable Developer Command Prompt (Windows)
      if: matrix.os == 'windows-2022'
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Install Boost
      uses: MarkusJx/install-boost@v2
      id: install-boost
      with:
        arch: ${{ matrix.boost_arch }}
        boost_version: 1.83.0
        platform_version: ${{ matrix.boost_platform_version }}
        toolset: ${{ matrix.boost_toolset }}

    - name: Enable mold linker (Linux)
      if: matrix.os == 'ubuntu-22.04'
      uses: rui314/setup-mold@v1

    - name: Configure CMake
      working-directory: ${{ github.workspace }}/build
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        cmake "${{ github.workspace }}" -G Ninja \
          "-DCMAKE_BUILD_TYPE=${{ inputs.build_type }}" \
          "-DBINEXPORT_ENABLE_IDAPRO=${{ secrets.IDASDK_SECRET != '' && inputs.enable_idapro_build }}" \
          "-DIdaSdk_ROOT_DIR=${{ github.workspace }}/build/idasdk_teams82" \
          "-DBINEXPORT_ENABLE_BINARYNINJA=${{ inputs.enable_binaryninja_build }}" \
          "-DBINEXPORT_BINARYNINJA_CHANNEL=${{ inputs.binaryninja_build_channel }}" \
          "-DBoost_INCLUDE_DIR=${{ steps.install-boost.outputs.BOOST_ROOT }}/include"

    - name: Build
      working-directory: ${{ github.workspace }}/build
      shell: bash
      run: cmake --build . --config ${{ inputs.build_type }} 

    - name: Test
      working-directory: ${{ github.workspace }}/build
      shell: bash
      run: ctest --build-config ${{ inputs.build_type }} --output-on-failure -R '^[A-Z]'

    - name: Upload Build Artifacts
      id: upload-build-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.base_artifact_filename }}-${{ runner.os }}-${{ runner.arch }}
        path: |
          ${{ github.workspace }}/build/binaryninja/binexport*
          ${{ github.workspace }}/build/ida/binexport*
          ${{ github.workspace }}/build/tools/binexport2dump*
